export const roles = [
  {
    id: 1,
    title: "경상좌수사",
    description:
      "수군을 지휘하는 최고 사령관\n작전 결정을 내리고 병력을 통솔함함",
    image: "/role1.png",
    detail: "/detail1.png",
    skill1:{
      name:'지도력',
      min:150,
      max:200,
    },
    skill2:{
      name:'결단력',
      min:130,
      max:180,
    },
    skill_description:'전체 수군을 지휘하고 위기에서 빠른 판단',
  },
  {
    id: 2,
    title: "첨 사",
    description: "좌수사를 보좌하는 부지휘관\n명령 전달과 현장 지휘를 맡음",
    image: "/role2.png",
    detail: "/detail2.png",
    skill1:{
      name:'돌파력',
      min:140,
      max:180,
    },
    skill2:{
      name:'명령권',
      min:120,
      max:160,
    },
    skill_description:'제2지휘관으로서의 전투 투입 및 명령 수행',
  },
  {
    id: 3,
    title: "사 수",
    description: "원거리 무기를 다루는 사격병\n적을 조준해 정확히 타격함",
    image: "/role3.png",
    detail: "/detail3.png",
    skill1:{
      name:'명중률',
      min:130,
      max:200,
    },
    skill2:{
      name:'관측력',
      min:100,
      max:160,
    },
    skill_description:'정확한 사격 능력 및 적 탐지',
  },
  {
    id: 4,
    title: "사 졸",
    description: "근접전을 담당하는 기본 병사\n기습과 백병전에 능함",
    image: "/role4.png",
    detail: "/detail4.png",
    skill1:{
      name:'기동력',
      min:110,
      max:160,
    },
    skill2:{
      name:'근접전투력',
      min:120,
      max:180,
    },
    skill_description:'빠른 이동과 백병전 전투',

  },
  {
    id: 5,
    title: "화 포 수",
    description: "화포를 운용하는 화력 지원병\n넓은 범위의 적을 공격함",
    image: "/role5.png",
    detail: "/detail5.png",
    skill1:{
      name:'화염공격력',
      min:150,
      max:210,
    },
    skill2:{
      name:'조준력',
      min:120,
      max:170,
    },
    skill_description:'포를 다루는 공격력과 조준 정확도',
  },

  {
    id: 6,
    title: "격 군",
    description: "노를 젓고 배를 조종하는 병사\n함선 운항을 책임짐",
    image: "/role6.png",
    detail: "/detail6.png",
    skill1:{
      name:'체력',
      min:130,
      max:180,
    },
    skill2:{
      name:'항해력',
      min:110,
      max:160,
    },
    skill_description:'노 젓기 지속력 및 조타 능력',
  },
  {
    id: 7,
    title: "나 장",
    description: "범죄자나 적을 추적하고 체포함\n질서 유지와 포박을 담당함",
    image: "/role7.png",
    detail: "/detail7.png",
    skill1:{
      name:'추적력',
      min:110,
      max:150,
    },
    skill2:{
      name:'제압력',
      min:120,
      max:160,
    },
    skill_description:'도주하는 적 추적 및 제압 능력',
  },
  {
    id: 8,
    title: "화 약 장",
    description: "화약과 폭발물을 제조·관리함\n전투용 폭탄을 다룸",
    image: "/role8.png",
    detail: "/detail8.png",
    skill1:{
      name:'제조력',
      min:120,
      max:160,
    },
    skill2:{
      name:'폭발력',
      min:140,
      max:200,
    },
    skill_description:'화약 및 폭탄 제조와 폭발 공격력',
  },
  {
    id: 9,
    title: "의 원",
    description: "병사들의 치료와 회복을 맡음\n질병 예방과 응급 처치를 담당함",
    image: "/role9.png",
    detail: "/detail9.png",
    skill1:{
      name:'치료력',
      min:130,
      max:180,
    },
    skill2:{
      name:'면역력',
      min:100,
      max:150,
    },
    skill_description:'병사 회복과 전염병 저항 능력',
  },
  {
    id: 10,
    title: "취 사 병",
    description: "병사들의 식사를 준비함\n보급과 체력 회복을 지원함",
    image: "/role10.png",
    detail: "/detail10.png",
    skill1:{
      name:'회복력',
      min:120,
      max:170,
    },
    skill2:{
      name:'사기력',
      min:110,
      max:150,
    },
    skill_description:'요리로 체력 회복 및 팀 사기 상승',
  },
  {
    id: 11,
    title: "거 지",
    description: "생존과 은신에 능한 인물\n위기 상황에서 빠르게 움직임",
    image: "/role11.png",
    detail: "/detail11.png",
    skill1:{
      name:'생존력',
      min:110,
      max:160,
    },
    skill2:{
      name:'회피력',
      min:90,
      max:130,
    },
    skill_description:'위기 생존 능력 및 은신/도주 능력',
  },
  {
    id: 12,
    title: "백성/상인",
    description: "비전투 민간인 캐릭터\n피난과 회피 행동에 특화됨됨",
    image: "/role12.png",
    detail: "/detail12.png",
    skill1:{
      name:'행운력',
      min:150,
      max:250,
    },
    skill2:{
      name:'순발력',
      min:100,
      max:140,
    },
    skill_description:'운에 의존한 위피 및 빠른 행동',
  },
];
